[package]
name = "rustee-jobs-rabbitmq"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "RabbitMQ quorum-queue job provider for Rustee"

[dependencies]
futures-util.workspace = true
lapin.workspace = true
rustee-jobs = { path = "../rustee-jobs", version = "0.1.0" }
thiserror.workspace = true
tokio.workspace = true

[dev-dependencies]
rustee-jobs-observability = { path = "../rustee-jobs-observability", version = "0.1.0" }
serde.workspace = true
tokio.workspace = true
uuid.workspace = true

[lints]
workspace = true
