//! Opaque cache keys, retention policy, eligibility, and provider-neutral cache contracts.

use std::{error::Error as StdError, fmt, time::Duration};

use futures_util::future::BoxFuture;
use rustee_ai::{AiPipeline, AiProvider, ChatRequest, ChatResponse, PipelineError};

const MAX_SCOPE_BYTES: usize = 128;
const SHA256_HEX_BYTES: usize = 64;

/// Maximum retention accepted by Rustee's standard response-cache contract.
///
/// Longer-lived prompt or completion retention requires an application-specific adapter and ADR.
pub const MAX_CACHE_TTL: Duration = Duration::from_secs(24 * 60 * 60);

/// Default response-cache TTL for an explicitly enabled cache.
pub const DEFAULT_CACHE_TTL: Duration = Duration::from_secs(300);

/// Application-selected opaque cache key.
///
/// `scope` must include the application tenant and any data, policy, model, or prompt-template
/// version that affects reuse. `fingerprint` is a lower-case SHA-256 hex digest generated by the
/// application; it must not be raw prompt content or an unsalted digest of sensitive input.
/// [`fmt::Debug`] redacts both values because they can reveal an application identity or correlation
/// handle.
#[derive(Clone, Eq, Ord, PartialEq, PartialOrd)]
pub struct AiCacheKey {
    scope: String,
    fingerprint: String,
}

impl AiCacheKey {
    /// Creates a bounded cache key from an application-owned scope and opaque fingerprint.
    ///
    /// # Errors
    ///
    /// Returns [`AiCacheConfigError`] when either public key component is unsafe.
    pub fn new(
        scope: impl Into<String>,
        fingerprint: impl Into<String>,
    ) -> Result<Self, AiCacheConfigError> {
        let scope = scope.into();
        if !valid_scope(&scope) {
            return Err(AiCacheConfigError::InvalidScope);
        }
        let fingerprint = fingerprint.into();
        if !valid_sha256_hex(&fingerprint) {
            return Err(AiCacheConfigError::InvalidFingerprint);
        }
        Ok(Self { scope, fingerprint })
    }

    /// Returns the application-owned isolation and version scope.
    #[must_use]
    pub fn scope(&self) -> &str {
        &self.scope
    }

    /// Returns the opaque lower-case SHA-256 fingerprint.
    #[must_use]
    pub fn fingerprint(&self) -> &str {
        &self.fingerprint
    }
}

impl fmt::Debug for AiCacheKey {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("AiCacheKey")
            .field("scope", &"[REDACTED]")
            .field("fingerprint", &"[REDACTED]")
            .finish()
    }
}

/// Explicit cache behavior when a cache read cannot complete.
#[derive(Clone, Copy, Debug, Default, Eq, PartialEq)]
pub enum AiCacheReadFailurePolicy {
    /// Do not invoke the provider when the cache cannot be read.
    FailClosed,
    /// Continue to the application executor without a cache write, and make the bypass visible in
    /// the returned status.
    #[default]
    Bypass,
}

/// Validated policy for a single response-cache adapter.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct AiCacheConfig {
    ttl: Duration,
    read_failure_policy: AiCacheReadFailurePolicy,
}

impl AiCacheConfig {
    /// Creates a cache policy with explicit non-zero, bounded retention.
    ///
    /// # Errors
    ///
    /// Returns [`AiCacheConfigError`] when `ttl` is zero or exceeds [`MAX_CACHE_TTL`].
    pub fn new(ttl: Duration) -> Result<Self, AiCacheConfigError> {
        if ttl.is_zero() {
            return Err(AiCacheConfigError::ZeroTtl);
        }
        if ttl > MAX_CACHE_TTL {
            return Err(AiCacheConfigError::TtlExceedsMaximum);
        }
        Ok(Self {
            ttl,
            read_failure_policy: AiCacheReadFailurePolicy::default(),
        })
    }

    /// Selects the policy applied only when a cache read fails.
    #[must_use]
    pub const fn with_read_failure_policy(
        mut self,
        read_failure_policy: AiCacheReadFailurePolicy,
    ) -> Self {
        self.read_failure_policy = read_failure_policy;
        self
    }

    /// Returns the explicit cache retention TTL.
    #[must_use]
    pub const fn ttl(self) -> Duration {
        self.ttl
    }

    /// Returns the policy for a failed cache read.
    #[must_use]
    pub const fn read_failure_policy(self) -> AiCacheReadFailurePolicy {
        self.read_failure_policy
    }
}

impl Default for AiCacheConfig {
    fn default() -> Self {
        Self::new(DEFAULT_CACHE_TTL).expect("default AI cache TTL must be valid")
    }
}

/// Invalid cache configuration or public cache-key input.
#[derive(Clone, Copy, Debug, Eq, PartialEq, thiserror::Error)]
pub enum AiCacheConfigError {
    /// Scope must be a bounded opaque identifier that cannot inject backend key syntax.
    #[error("AI cache scope must use bounded ASCII letters, digits, underscore, hyphen, or dot")]
    InvalidScope,
    /// The framework accepts only fixed-length lower-case SHA-256 hex fingerprints.
    #[error("AI cache fingerprint must be a lower-case SHA-256 hexadecimal digest")]
    InvalidFingerprint,
    /// Cache retention must always be explicit and positive.
    #[error("AI cache TTL must be greater than zero")]
    ZeroTtl,
    /// Long-lived prompt or completion retention needs an application-specific adapter and ADR.
    #[error("AI cache TTL must not exceed one day")]
    TtlExceedsMaximum,
    /// The in-memory implementation has a bounded entry count.
    #[error("AI in-memory cache capacity must be between one and 10,000 entries")]
    InvalidInMemoryCapacity,
}

/// A response proven safe for this cache contract.
///
/// The entry contains a completion but cannot contain a model-requested tool call. Its debug form
/// delegates to the redacted [`ChatResponse`] debug implementation.
#[derive(Clone)]
pub struct AiCacheEntry {
    response: ChatResponse,
}

impl AiCacheEntry {
    /// Creates a cache entry for a non-tool-call response.
    ///
    /// # Errors
    ///
    /// Returns [`AiCacheEligibilityError::ResponseContainsToolCalls`] when the model requested a
    /// tool. Tool-call responses are interaction state, not reusable cached completions.
    pub fn new(response: ChatResponse) -> Result<Self, AiCacheEligibilityError> {
        if !response.tool_calls().is_empty() {
            return Err(AiCacheEligibilityError::ResponseContainsToolCalls);
        }
        Ok(Self { response })
    }

    /// Returns the cached response. Treat content as application data.
    #[must_use]
    pub const fn response(&self) -> &ChatResponse {
        &self.response
    }

    /// Consumes the entry and returns its response.
    #[must_use]
    pub fn into_response(self) -> ChatResponse {
        self.response
    }
}

impl fmt::Debug for AiCacheEntry {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("AiCacheEntry")
            .field("response", &self.response)
            .finish()
    }
}

/// A request or response that cannot be reused by the response cache.
#[derive(Clone, Copy, Debug, Eq, PartialEq, thiserror::Error)]
pub enum AiCacheEligibilityError {
    /// The request declares tools, so a model response may begin an interaction.
    #[error("AI cache does not accept requests with declared tools")]
    RequestDeclaresTools,
    /// The request contains an application-approved tool result from a prior interaction.
    #[error("AI cache does not accept requests with tool results")]
    RequestContainsToolResults,
    /// The response asks the application to run one or more tools.
    #[error("AI cache does not accept responses containing model tool calls")]
    ResponseContainsToolCalls,
}

/// Explicit storage for validated response-cache entries.
///
/// Implementations retain raw completion content only under the application's opaque key. They
/// must not log entry content or make cross-scope lookup possible. Namespace-wide purges are not
/// provided: applications invalidate an exact key or advance their versioned scope and let TTL
/// expire old entries.
pub trait AiResponseCache: Clone + Send + Sync + 'static {
    /// Backend-specific cache failure.
    type Error: StdError + Send + Sync + 'static;

    /// Looks up one exact, application-owned cache key.
    fn get(&self, key: AiCacheKey)
    -> BoxFuture<'static, Result<Option<AiCacheEntry>, Self::Error>>;

    /// Stores a response that already passed the tool-call eligibility boundary.
    fn put(
        &self,
        key: AiCacheKey,
        entry: AiCacheEntry,
        ttl: Duration,
    ) -> BoxFuture<'static, Result<(), Self::Error>>;

    /// Invalidates one exact application-owned cache key.
    fn invalidate(&self, key: AiCacheKey) -> BoxFuture<'static, Result<(), Self::Error>>;
}

/// Application-selected path for a non-streaming completion that can participate in caching.
///
/// Implement this around the same budget, authorization, usage-ledger, and advisor pipeline used
/// by normal requests. The cache adapter never opens a streaming request or retries a provider.
pub trait AiCacheExecutor: Clone + Send + Sync + 'static {
    /// Application completion failure.
    type Error: StdError + Send + Sync + 'static;

    /// Performs exactly one already-governed non-streaming completion.
    fn complete_for_cache(
        &self,
        request: ChatRequest,
    ) -> BoxFuture<'static, Result<ChatResponse, Self::Error>>;
}

impl<P> AiCacheExecutor for AiPipeline<P>
where
    P: AiProvider,
{
    type Error = PipelineError<P::Error>;

    fn complete_for_cache(
        &self,
        request: ChatRequest,
    ) -> BoxFuture<'static, Result<ChatResponse, Self::Error>> {
        let pipeline = self.clone();
        Box::pin(async move { pipeline.complete(request).await })
    }
}

fn valid_scope(scope: &str) -> bool {
    !scope.is_empty()
        && scope.len() <= MAX_SCOPE_BYTES
        && scope
            .bytes()
            .all(|byte| byte.is_ascii_alphanumeric() || matches!(byte, b'_' | b'-' | b'.'))
}

fn valid_sha256_hex(fingerprint: &str) -> bool {
    fingerprint.len() == SHA256_HEX_BYTES
        && fingerprint
            .bytes()
            .all(|byte| byte.is_ascii_digit() || matches!(byte, b'a'..=b'f'))
}
