//! Explicit, tenant-scoped AI response-cache contracts.
//!
//! The application derives an opaque SHA-256 fingerprint after it has authorized and normalized a
//! request. This crate never hashes, serializes, logs, or otherwise retains a prompt in order to
//! construct a cache key. Cache lookup is limited to non-streaming requests without declared
//! tools or prior tool results, and responses containing model tool calls are never stored.
//!
//! Cache read failure handling is explicit. A cache write failure is reported as a status after a
//! successful provider completion; it never turns into an automatic provider retry.

use std::{
    collections::BTreeMap,
    error::Error as StdError,
    fmt,
    sync::{Arc, Mutex},
    time::{Duration, Instant},
};

use futures_util::future::BoxFuture;
use rustee_ai::{AiPipeline, AiProvider, ChatRequest, ChatResponse, PipelineError};

const MAX_SCOPE_BYTES: usize = 128;
const SHA256_HEX_BYTES: usize = 64;
const MAX_CACHE_TTL: Duration = Duration::from_secs(24 * 60 * 60);
const MAX_IN_MEMORY_ENTRIES: usize = 10_000;

/// Default response-cache TTL for an explicitly enabled cache.
pub const DEFAULT_CACHE_TTL: Duration = Duration::from_secs(300);

/// Application-selected opaque cache key.
///
/// `scope` must include the application tenant and any data, policy, model, or prompt-template
/// version that affects reuse. `fingerprint` is a lower-case SHA-256 hex digest generated by the
/// application; it must not be raw prompt content or an unsalted digest of sensitive input.
#[derive(Clone, Eq, Ord, PartialEq, PartialOrd)]
pub struct AiCacheKey {
    scope: String,
    fingerprint: String,
}

impl AiCacheKey {
    /// Creates a bounded cache key from an application-owned scope and opaque fingerprint.
    ///
    /// # Errors
    ///
    /// Returns [`AiCacheConfigError`] when either public key component is unsafe.
    pub fn new(
        scope: impl Into<String>,
        fingerprint: impl Into<String>,
    ) -> Result<Self, AiCacheConfigError> {
        let scope = scope.into();
        if !valid_scope(&scope) {
            return Err(AiCacheConfigError::InvalidScope);
        }
        let fingerprint = fingerprint.into();
        if !valid_sha256_hex(&fingerprint) {
            return Err(AiCacheConfigError::InvalidFingerprint);
        }
        Ok(Self { scope, fingerprint })
    }

    /// Returns the application-owned isolation and version scope.
    #[must_use]
    pub fn scope(&self) -> &str {
        &self.scope
    }

    /// Returns the opaque lower-case SHA-256 fingerprint.
    #[must_use]
    pub fn fingerprint(&self) -> &str {
        &self.fingerprint
    }
}

impl fmt::Debug for AiCacheKey {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("AiCacheKey")
            .field("scope", &self.scope)
            .field("fingerprint", &self.fingerprint)
            .finish()
    }
}

/// Explicit cache behavior when a cache read cannot complete.
#[derive(Clone, Copy, Debug, Default, Eq, PartialEq)]
pub enum AiCacheReadFailurePolicy {
    /// Do not invoke the provider when the cache cannot be read.
    FailClosed,
    /// Continue to the application executor, but make the bypass visible in the returned status.
    #[default]
    Bypass,
}

/// Validated policy for a single response-cache adapter.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct AiCacheConfig {
    ttl: Duration,
    read_failure_policy: AiCacheReadFailurePolicy,
}

impl AiCacheConfig {
    /// Creates a cache policy with explicit non-zero, bounded retention.
    ///
    /// # Errors
    ///
    /// Returns [`AiCacheConfigError`] when `ttl` is zero or exceeds one day.
    pub fn new(ttl: Duration) -> Result<Self, AiCacheConfigError> {
        if ttl.is_zero() {
            return Err(AiCacheConfigError::ZeroTtl);
        }
        if ttl > MAX_CACHE_TTL {
            return Err(AiCacheConfigError::TtlExceedsMaximum);
        }
        Ok(Self {
            ttl,
            read_failure_policy: AiCacheReadFailurePolicy::default(),
        })
    }

    /// Selects the policy applied only when a cache read fails.
    #[must_use]
    pub const fn with_read_failure_policy(
        mut self,
        read_failure_policy: AiCacheReadFailurePolicy,
    ) -> Self {
        self.read_failure_policy = read_failure_policy;
        self
    }

    /// Returns the explicit cache retention TTL.
    #[must_use]
    pub const fn ttl(self) -> Duration {
        self.ttl
    }

    /// Returns the policy for a failed cache read.
    #[must_use]
    pub const fn read_failure_policy(self) -> AiCacheReadFailurePolicy {
        self.read_failure_policy
    }
}

impl Default for AiCacheConfig {
    fn default() -> Self {
        Self::new(DEFAULT_CACHE_TTL).expect("default AI cache TTL must be valid")
    }
}

/// Invalid cache configuration or public cache-key input.
#[derive(Clone, Copy, Debug, Eq, PartialEq, thiserror::Error)]
pub enum AiCacheConfigError {
    /// Scope must be a bounded opaque identifier that cannot inject backend key syntax.
    #[error("AI cache scope must use bounded ASCII letters, digits, underscore, hyphen, or dot")]
    InvalidScope,
    /// The framework accepts only fixed-length lower-case SHA-256 hex fingerprints.
    #[error("AI cache fingerprint must be a lower-case SHA-256 hexadecimal digest")]
    InvalidFingerprint,
    /// Cache retention must always be explicit and positive.
    #[error("AI cache TTL must be greater than zero")]
    ZeroTtl,
    /// Long-lived prompt or completion retention needs an application-specific adapter and ADR.
    #[error("AI cache TTL must not exceed one day")]
    TtlExceedsMaximum,
    /// The in-memory implementation has a bounded entry count.
    #[error("AI in-memory cache capacity must be between one and 10,000 entries")]
    InvalidInMemoryCapacity,
}

/// A response proven safe for this cache contract.
///
/// The entry contains a completion but cannot contain a model-requested tool call. Its debug form
/// delegates to the redacted [`ChatResponse`] debug implementation.
#[derive(Clone)]
pub struct AiCacheEntry {
    response: ChatResponse,
}

impl AiCacheEntry {
    /// Creates a cache entry for a non-tool-call response.
    ///
    /// # Errors
    ///
    /// Returns [`AiCacheEligibilityError::ResponseContainsToolCalls`] when the model requested a
    /// tool. Tool-call responses are interaction state, not reusable cached completions.
    pub fn new(response: ChatResponse) -> Result<Self, AiCacheEligibilityError> {
        if !response.tool_calls().is_empty() {
            return Err(AiCacheEligibilityError::ResponseContainsToolCalls);
        }
        Ok(Self { response })
    }

    /// Returns the cached response. Treat content as application data.
    #[must_use]
    pub const fn response(&self) -> &ChatResponse {
        &self.response
    }

    /// Consumes the entry and returns its response.
    #[must_use]
    pub fn into_response(self) -> ChatResponse {
        self.response
    }
}

impl fmt::Debug for AiCacheEntry {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("AiCacheEntry")
            .field("response", &self.response)
            .finish()
    }
}

/// A request or response that cannot be reused by the response cache.
#[derive(Clone, Copy, Debug, Eq, PartialEq, thiserror::Error)]
pub enum AiCacheEligibilityError {
    /// The request declares tools, so a model response may begin an interaction.
    #[error("AI cache does not accept requests with declared tools")]
    RequestDeclaresTools,
    /// The request contains an application-approved tool result from a prior interaction.
    #[error("AI cache does not accept requests with tool results")]
    RequestContainsToolResults,
    /// The response asks the application to run one or more tools.
    #[error("AI cache does not accept responses containing model tool calls")]
    ResponseContainsToolCalls,
}

/// Explicit storage for validated response-cache entries.
///
/// Implementations retain raw completion content only under the application's opaque key. They
/// must not log entry content or make cross-scope lookup possible. Namespace-wide purges are not
/// provided: applications invalidate an exact key or advance their versioned scope and let TTL
/// expire old entries.
pub trait AiResponseCache: Clone + Send + Sync + 'static {
    /// Backend-specific cache failure.
    type Error: StdError + Send + Sync + 'static;

    /// Looks up one exact, application-owned cache key.
    fn get(&self, key: AiCacheKey)
    -> BoxFuture<'static, Result<Option<AiCacheEntry>, Self::Error>>;

    /// Stores a response that already passed the tool-call eligibility boundary.
    fn put(
        &self,
        key: AiCacheKey,
        entry: AiCacheEntry,
        ttl: Duration,
    ) -> BoxFuture<'static, Result<(), Self::Error>>;

    /// Invalidates one exact application-owned cache key.
    fn invalidate(&self, key: AiCacheKey) -> BoxFuture<'static, Result<(), Self::Error>>;
}

/// Application-selected path for a non-streaming completion that can participate in caching.
///
/// Implement this around the same budget, authorization, usage-ledger, and advisor pipeline used
/// by normal requests. The cache adapter never opens a streaming request or retries a provider.
pub trait AiCacheExecutor: Clone + Send + Sync + 'static {
    /// Application completion failure.
    type Error: StdError + Send + Sync + 'static;

    /// Performs exactly one already-governed non-streaming completion.
    fn complete_for_cache(
        &self,
        request: ChatRequest,
    ) -> BoxFuture<'static, Result<ChatResponse, Self::Error>>;
}

impl<P> AiCacheExecutor for AiPipeline<P>
where
    P: AiProvider,
{
    type Error = PipelineError<P::Error>;

    fn complete_for_cache(
        &self,
        request: ChatRequest,
    ) -> BoxFuture<'static, Result<ChatResponse, Self::Error>> {
        let pipeline = self.clone();
        Box::pin(async move { pipeline.complete(request).await })
    }
}

/// Status of one completion's explicit cache interaction.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum AiCacheStatus {
    /// A validated cached response was returned and no provider call occurred.
    Hit,
    /// The provider completed once and its eligible response was stored.
    MissStored,
    /// The provider completed once but its eligible response could not be stored.
    MissStoreFailed,
    /// The request was intentionally not eligible for cache lookup or storage.
    BypassedIneligibleRequest,
    /// A cache read failed under the explicit bypass policy; one provider call followed.
    BypassedReadFailure,
    /// The provider returned a model tool call, so the response was not stored.
    MissIneligibleResponse,
}

/// One response with its cache outcome.
#[derive(Clone)]
pub struct AiCachedResponse {
    response: ChatResponse,
    cache_status: AiCacheStatus,
}

impl AiCachedResponse {
    /// Returns the application-visible completion.
    #[must_use]
    pub const fn response(&self) -> &ChatResponse {
        &self.response
    }

    /// Consumes the result and returns its completion.
    #[must_use]
    pub fn into_response(self) -> ChatResponse {
        self.response
    }

    /// Returns the explicit cache outcome for usage and observability accounting.
    #[must_use]
    pub const fn cache_status(&self) -> AiCacheStatus {
        self.cache_status
    }
}

impl fmt::Debug for AiCachedResponse {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("AiCachedResponse")
            .field("response", &self.response)
            .field("cache_status", &self.cache_status)
            .finish()
    }
}

/// Explicit cache adapter around an application-governed completion executor.
#[derive(Clone)]
pub struct AiCachedCompletion<E, C> {
    executor: E,
    cache: C,
    config: AiCacheConfig,
}

impl<E, C> AiCachedCompletion<E, C> {
    /// Creates one cache adapter with a validated policy.
    #[must_use]
    pub const fn new(executor: E, cache: C, config: AiCacheConfig) -> Self {
        Self {
            executor,
            cache,
            config,
        }
    }

    /// Returns the explicit cache configuration.
    #[must_use]
    pub const fn config(&self) -> AiCacheConfig {
        self.config
    }
}

impl<E, C> fmt::Debug for AiCachedCompletion<E, C> {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("AiCachedCompletion")
            .field("config", &self.config)
            .finish_non_exhaustive()
    }
}

impl<E, C> AiCachedCompletion<E, C>
where
    E: AiCacheExecutor,
    C: AiResponseCache,
{
    /// Completes one request through an explicit cache key.
    ///
    /// The caller must derive `key` after authorization and include tenant, model, prompt/data
    /// revision, and policy versions in its scope or fingerprint. This method does not cache tool
    /// interaction requests/responses, streaming calls, provider failures, or cache errors.
    ///
    /// # Errors
    ///
    /// Returns an executor failure, a fail-closed read failure, or an impossible unsafe cache
    /// entry. Cache write failures are returned as [`AiCacheStatus::MissStoreFailed`] after the
    /// one completed provider response and never trigger a retry.
    pub async fn complete(
        &self,
        request: ChatRequest,
        key: AiCacheKey,
    ) -> Result<AiCachedResponse, AiCachedCompletionError<E::Error, C::Error>> {
        if request_eligibility(&request).is_err() {
            return self
                .complete_without_cache(request, AiCacheStatus::BypassedIneligibleRequest)
                .await
                .map_err(|source| AiCachedCompletionError::Executor { source });
        }

        let status_after_miss = match self.cache.get(key.clone()).await {
            Ok(Some(entry)) => {
                return Ok(AiCachedResponse {
                    response: entry.into_response(),
                    cache_status: AiCacheStatus::Hit,
                });
            }
            Ok(None) => AiCacheStatus::MissStored,
            Err(source) => match self.config.read_failure_policy() {
                AiCacheReadFailurePolicy::FailClosed => {
                    return Err(AiCachedCompletionError::CacheRead { source });
                }
                AiCacheReadFailurePolicy::Bypass => AiCacheStatus::BypassedReadFailure,
            },
        };

        let response = self
            .executor
            .complete_for_cache(request)
            .await
            .map_err(|source| AiCachedCompletionError::Executor { source })?;
        let entry = match AiCacheEntry::new(response.clone()) {
            Ok(entry) => entry,
            Err(AiCacheEligibilityError::ResponseContainsToolCalls) => {
                return Ok(AiCachedResponse {
                    response,
                    cache_status: AiCacheStatus::MissIneligibleResponse,
                });
            }
            Err(error) => return Err(AiCachedCompletionError::UnsafeCacheEntry { error }),
        };
        let cache_status = match self.cache.put(key, entry, self.config.ttl()).await {
            Ok(()) => status_after_miss,
            Err(_) => AiCacheStatus::MissStoreFailed,
        };
        Ok(AiCachedResponse {
            response,
            cache_status,
        })
    }

    /// Invalidates one exact key; broad tenant deletion remains application-owned.
    ///
    /// # Errors
    ///
    /// Returns a sanitized backend failure when the exact deletion cannot be completed.
    pub async fn invalidate(
        &self,
        key: AiCacheKey,
    ) -> Result<(), AiCacheInvalidationError<C::Error>> {
        self.cache
            .invalidate(key)
            .await
            .map_err(|source| AiCacheInvalidationError { source })
    }

    async fn complete_without_cache(
        &self,
        request: ChatRequest,
        cache_status: AiCacheStatus,
    ) -> Result<AiCachedResponse, E::Error> {
        let response = self.executor.complete_for_cache(request).await?;
        Ok(AiCachedResponse {
            response,
            cache_status,
        })
    }
}

/// One sanitized cache-adapter failure.
#[derive(Debug, thiserror::Error)]
pub enum AiCachedCompletionError<ExecutorError, CacheError> {
    /// The application-governed executor failed. No cache or provider retry occurred here.
    #[error("AI cached completion executor failed")]
    Executor {
        /// Application completion failure.
        #[source]
        source: ExecutorError,
    },
    /// The cache read failed under the explicit fail-closed policy, so no provider call occurred.
    #[error("AI response cache read failed")]
    CacheRead {
        /// Backend cache failure.
        #[source]
        source: CacheError,
    },
    /// An entry somehow bypassed the cache eligibility contract.
    #[error("AI response cache entry was not eligible")]
    UnsafeCacheEntry {
        /// Rejected eligibility condition.
        #[source]
        error: AiCacheEligibilityError,
    },
}

/// A sanitized exact-key cache invalidation failure.
#[derive(Debug, thiserror::Error)]
#[error("AI response cache invalidation failed")]
pub struct AiCacheInvalidationError<CacheError> {
    /// Backend cache failure.
    #[source]
    pub source: CacheError,
}

/// Bounded in-memory cache intended for deterministic local development and tests.
///
/// It does not provide distributed invalidation, encryption, or eviction. Production deployments
/// should use an application-reviewed durable adapter with tenant erase and retention procedures.
#[derive(Clone)]
pub struct InMemoryAiResponseCache {
    state: Arc<Mutex<InMemoryState>>,
    capacity: usize,
}

#[derive(Default)]
struct InMemoryState {
    entries: BTreeMap<AiCacheKey, InMemoryEntry>,
}

#[derive(Clone)]
struct InMemoryEntry {
    entry: AiCacheEntry,
    expires_at: Instant,
}

impl InMemoryAiResponseCache {
    /// Creates an in-memory cache with a fixed maximum entry count.
    ///
    /// # Errors
    ///
    /// Returns [`AiCacheConfigError::InvalidInMemoryCapacity`] outside the one-to-10,000 bound.
    pub fn new(capacity: usize) -> Result<Self, AiCacheConfigError> {
        if !(1..=MAX_IN_MEMORY_ENTRIES).contains(&capacity) {
            return Err(AiCacheConfigError::InvalidInMemoryCapacity);
        }
        Ok(Self {
            state: Arc::new(Mutex::new(InMemoryState::default())),
            capacity,
        })
    }

    /// Returns the fixed maximum number of unexpired entries.
    #[must_use]
    pub const fn capacity(&self) -> usize {
        self.capacity
    }
}

impl fmt::Debug for InMemoryAiResponseCache {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        let entries = self
            .state
            .lock()
            .map(|state| state.entries.len())
            .unwrap_or_default();
        formatter
            .debug_struct("InMemoryAiResponseCache")
            .field("capacity", &self.capacity)
            .field("retained_entries", &entries)
            .finish()
    }
}

/// In-memory cache storage failure.
#[derive(Clone, Copy, Debug, Eq, PartialEq, thiserror::Error)]
pub enum InMemoryAiResponseCacheError {
    /// A cache TTL must stay explicit and positive even for direct store calls.
    #[error("AI in-memory cache TTL must be greater than zero")]
    ZeroTtl,
    /// The cache is full and deliberately does not evict a live entry implicitly.
    #[error("AI in-memory cache capacity is exhausted")]
    CapacityExhausted,
    /// A poisoned lock prevents retaining or returning application data.
    #[error("AI in-memory cache state is unavailable")]
    StateUnavailable,
}

impl AiResponseCache for InMemoryAiResponseCache {
    type Error = InMemoryAiResponseCacheError;

    fn get(
        &self,
        key: AiCacheKey,
    ) -> BoxFuture<'static, Result<Option<AiCacheEntry>, Self::Error>> {
        let state = self.state.clone();
        Box::pin(async move {
            let mut state = state
                .lock()
                .map_err(|_| InMemoryAiResponseCacheError::StateUnavailable)?;
            let now = Instant::now();
            let result = state
                .entries
                .get(&key)
                .and_then(|entry| (entry.expires_at > now).then(|| entry.entry.clone()));
            if result.is_none() {
                state.entries.remove(&key);
            }
            Ok(result)
        })
    }

    fn put(
        &self,
        key: AiCacheKey,
        entry: AiCacheEntry,
        ttl: Duration,
    ) -> BoxFuture<'static, Result<(), Self::Error>> {
        let state = self.state.clone();
        let capacity = self.capacity;
        Box::pin(async move {
            if ttl.is_zero() {
                return Err(InMemoryAiResponseCacheError::ZeroTtl);
            }
            let mut state = state
                .lock()
                .map_err(|_| InMemoryAiResponseCacheError::StateUnavailable)?;
            let now = Instant::now();
            state.entries.retain(|_, value| value.expires_at > now);
            if !state.entries.contains_key(&key) && state.entries.len() == capacity {
                return Err(InMemoryAiResponseCacheError::CapacityExhausted);
            }
            state.entries.insert(
                key,
                InMemoryEntry {
                    entry,
                    expires_at: now + ttl,
                },
            );
            Ok(())
        })
    }

    fn invalidate(&self, key: AiCacheKey) -> BoxFuture<'static, Result<(), Self::Error>> {
        let state = self.state.clone();
        Box::pin(async move {
            let mut state = state
                .lock()
                .map_err(|_| InMemoryAiResponseCacheError::StateUnavailable)?;
            state.entries.remove(&key);
            Ok(())
        })
    }
}

fn request_eligibility(request: &ChatRequest) -> Result<(), AiCacheEligibilityError> {
    if !request.tools().is_empty() {
        return Err(AiCacheEligibilityError::RequestDeclaresTools);
    }
    if !request.tool_results().is_empty() {
        return Err(AiCacheEligibilityError::RequestContainsToolResults);
    }
    Ok(())
}

fn valid_scope(scope: &str) -> bool {
    !scope.is_empty()
        && scope.len() <= MAX_SCOPE_BYTES
        && scope
            .bytes()
            .all(|byte| byte.is_ascii_alphanumeric() || matches!(byte, b'_' | b'-' | b'.'))
}

fn valid_sha256_hex(fingerprint: &str) -> bool {
    fingerprint.len() == SHA256_HEX_BYTES
        && fingerprint
            .bytes()
            .all(|byte| byte.is_ascii_digit() || matches!(byte, b'a'..=b'f'))
}

#[cfg(test)]
mod tests {
    use std::time::Duration;

    use futures_util::future::BoxFuture;
    use rustee_ai::{
        AiPipeline, ChatMessage, ChatRequest, ChatResponse, MessageRole, ToolDefinition, Usage,
    };
    use rustee_ai_test::RecordedAiProvider;

    use super::{
        AiCacheConfig, AiCacheConfigError, AiCacheEntry, AiCacheKey, AiCacheReadFailurePolicy,
        AiCacheStatus, AiCachedCompletion, AiCachedCompletionError, AiResponseCache,
        InMemoryAiResponseCache,
    };

    #[derive(Clone, Copy, Debug, thiserror::Error)]
    #[error("test cache unavailable")]
    enum TestCacheError {
        Unavailable,
    }

    #[derive(Clone, Copy)]
    struct ReadFailingCache;

    impl AiResponseCache for ReadFailingCache {
        type Error = TestCacheError;

        fn get(
            &self,
            _key: AiCacheKey,
        ) -> BoxFuture<'static, Result<Option<AiCacheEntry>, Self::Error>> {
            Box::pin(async { Err(TestCacheError::Unavailable) })
        }

        fn put(
            &self,
            _key: AiCacheKey,
            _entry: AiCacheEntry,
            _ttl: Duration,
        ) -> BoxFuture<'static, Result<(), Self::Error>> {
            Box::pin(async { Ok(()) })
        }

        fn invalidate(&self, _key: AiCacheKey) -> BoxFuture<'static, Result<(), Self::Error>> {
            Box::pin(async { Ok(()) })
        }
    }

    #[derive(Clone, Copy)]
    struct WriteFailingCache;

    impl AiResponseCache for WriteFailingCache {
        type Error = TestCacheError;

        fn get(
            &self,
            _key: AiCacheKey,
        ) -> BoxFuture<'static, Result<Option<AiCacheEntry>, Self::Error>> {
            Box::pin(async { Ok(None) })
        }

        fn put(
            &self,
            _key: AiCacheKey,
            _entry: AiCacheEntry,
            _ttl: Duration,
        ) -> BoxFuture<'static, Result<(), Self::Error>> {
            Box::pin(async { Err(TestCacheError::Unavailable) })
        }

        fn invalidate(&self, _key: AiCacheKey) -> BoxFuture<'static, Result<(), Self::Error>> {
            Box::pin(async { Ok(()) })
        }
    }

    fn request() -> ChatRequest {
        ChatRequest::new(
            "support.default",
            [ChatMessage::new(MessageRole::User, "private customer prompt").unwrap()],
        )
        .unwrap()
    }

    fn response(id: &str, content: &str) -> ChatResponse {
        ChatResponse::new(
            id,
            "provider-model",
            content,
            [],
            Usage {
                input_tokens: 3,
                output_tokens: 5,
            },
        )
        .unwrap()
    }

    fn key() -> AiCacheKey {
        AiCacheKey::new(
            "tenant-a.model-v3.policy-v2",
            "0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f",
        )
        .unwrap()
    }

    #[test]
    fn cache_key_and_retention_are_bounded_and_opaque() {
        assert!(AiCacheKey::new("tenant-a", "f".repeat(64)).is_ok());
        assert!(AiCacheKey::new("tenant a", "f".repeat(64)).is_err());
        assert!(AiCacheKey::new("tenant-a", "prompt content").is_err());
        assert_eq!(
            AiCacheConfig::new(Duration::ZERO).unwrap_err(),
            AiCacheConfigError::ZeroTtl
        );
        assert_eq!(
            AiCacheConfig::new(Duration::from_secs(24 * 60 * 60 + 1)).unwrap_err(),
            AiCacheConfigError::TtlExceedsMaximum
        );
    }

    #[tokio::test]
    async fn cache_hit_never_invokes_the_provider_and_debug_stays_redacted() {
        let cache = InMemoryAiResponseCache::new(2).unwrap();
        cache
            .put(
                key(),
                AiCacheEntry::new(response("cached", "private cached answer")).unwrap(),
                Duration::from_secs(60),
            )
            .await
            .unwrap();
        let provider = RecordedAiProvider::new();
        let completion = AiCachedCompletion::new(
            AiPipeline::new(provider.clone()),
            cache,
            AiCacheConfig::default(),
        );

        let result = completion.complete(request(), key()).await.unwrap();

        assert_eq!(result.cache_status(), AiCacheStatus::Hit);
        assert_eq!(result.response().content(), "private cached answer");
        assert!(provider.recorded_requests().is_empty());
        let debug = format!("{result:?}");
        assert!(!debug.contains("private cached answer"));
        assert!(!debug.contains("private customer prompt"));
    }

    #[tokio::test]
    async fn miss_stores_once_and_later_hit_preserves_usage_without_a_second_call() {
        let cache = InMemoryAiResponseCache::new(2).unwrap();
        let provider = RecordedAiProvider::new();
        provider.queue_completion(response("fresh", "first answer"));
        let completion = AiCachedCompletion::new(
            AiPipeline::new(provider.clone()),
            cache,
            AiCacheConfig::new(Duration::from_secs(60)).unwrap(),
        );

        let first = completion.complete(request(), key()).await.unwrap();
        let second = completion.complete(request(), key()).await.unwrap();

        assert_eq!(first.cache_status(), AiCacheStatus::MissStored);
        assert_eq!(second.cache_status(), AiCacheStatus::Hit);
        assert_eq!(second.response().usage().total_tokens(), 8);
        assert_eq!(provider.recorded_requests().len(), 1);
        completion.invalidate(key()).await.unwrap();
    }

    #[tokio::test]
    async fn tool_interaction_requests_and_responses_are_never_cached() {
        let cache = InMemoryAiResponseCache::new(2).unwrap();
        let provider = RecordedAiProvider::new();
        provider.queue_completion(response("one", "first answer"));
        let completion = AiCachedCompletion::new(
            AiPipeline::new(provider.clone()),
            cache,
            AiCacheConfig::default(),
        );
        let request = request().with_tools([ToolDefinition::new(
            "lookup",
            serde_json::json!({"type": "object"}),
        )
        .unwrap()]);

        let result = completion.complete(request, key()).await.unwrap();

        assert_eq!(
            result.cache_status(),
            AiCacheStatus::BypassedIneligibleRequest
        );
        assert_eq!(provider.recorded_requests().len(), 1);
        assert!(
            AiCacheEntry::new(
                ChatResponse::new(
                    "tool-response",
                    "provider-model",
                    "",
                    [
                        rustee_ai::ToolCall::new("call-1", "lookup", serde_json::json!({}))
                            .unwrap()
                    ],
                    Usage::default(),
                )
                .unwrap(),
            )
            .is_err()
        );
    }

    #[tokio::test]
    async fn fail_closed_cache_read_does_not_call_the_provider() {
        let provider = RecordedAiProvider::new();
        provider.queue_completion(response("should-not-run", "response"));
        let completion = AiCachedCompletion::new(
            AiPipeline::new(provider.clone()),
            ReadFailingCache,
            AiCacheConfig::default().with_read_failure_policy(AiCacheReadFailurePolicy::FailClosed),
        );

        let error = completion.complete(request(), key()).await.unwrap_err();

        assert!(matches!(error, AiCachedCompletionError::CacheRead { .. }));
        assert!(provider.recorded_requests().is_empty());
    }

    #[tokio::test]
    async fn cache_write_failure_returns_the_completed_response_without_provider_retry() {
        let provider = RecordedAiProvider::new();
        provider.queue_completion(response("write-failed", "completed once"));
        let completion = AiCachedCompletion::new(
            AiPipeline::new(provider.clone()),
            WriteFailingCache,
            AiCacheConfig::default(),
        );

        let result = completion.complete(request(), key()).await.unwrap();

        assert_eq!(result.cache_status(), AiCacheStatus::MissStoreFailed);
        assert_eq!(result.response().content(), "completed once");
        assert_eq!(provider.recorded_requests().len(), 1);
    }
}
