[package]
name = "rustee-redis"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Redis connection and explicit cache helpers for Rustee"

[dependencies]
redis.workspace = true
rustee-json = { path = "../rustee-json", version = "0.1.0" }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true

[dev-dependencies]
tokio.workspace = true
uuid.workspace = true

[lints]
workspace = true
